# Generated by Django 4.1.7 on 2023-03-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
