# Generated by Django 4.1.7 on 2023-03-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_word_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'permissions': [('change_blog_title', "Peut changer le titre d'un billet")]},
        ),
    ]
